from time import sleep
print("\033[1;30mHello! Welcome to a password setup application.")
sleep(1)
passCode = input("Type your new password: ")
sleep(1)
print("Saving password...")
sleep(1)
print("Password updated succesfully.")
sleep(1)
passCodeQuestion = input("What's the password? ")
sleep(1)
print("Checking the password.")
sleep(1)
while passCodeQuestion != passCode:
    print("\033[1;31mINCORRECT.")
    sleep(1)
    passCodeQuestion = input("\033[1;30mType again: ")
    sleep(1)
print("Checking the password.")
sleep(1)
if passCodeQuestion == passCode:
    print("\033[1;34mCorrect.")
    sleep(1)
print("\033[1;30mEnd")
